[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["liom_toolkit"]

[project]
name = "liom-toolkit"
readme = "README.md"
version = "2025.06.12"
license = "GPL-3.0-or-later"
requires-python = ">= 3.11"
authors = [
    { name = "Frederic Lesage", email = "frederic.lesage@polymtl.ca" },
    { name = "Frans Irgolitsch", email = "frans.irgolitsch@polymtl.ca" }
]
description = "LIOM Toolkit is a Python package for processing and analyzing microscopy data, providing tools for image segmentation, registration, and analysis."
keywords = ["bioinformatics", "neuroinformatics", "lightsheet", "microscopy", "liom", "segmentation", "registration", "image processing",
    "deep learning"]

dependencies = [
    'tqdm',
    'scikit-image',
    'ome-zarr>=0.9.0',
    'nibabel',
    'zarr',
    'h5py',
    'pynrrd',
    'PyWavelets',
    'SimpleITK',
    'dask',
    "bokeh>=3.1.0", # Bokeh is used for the dask dashboard
    'distributed',
    'opencv-python',
    'patchify',
    'natsort',
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Programming Language :: Python :: 3.11"
]

[project.optional-dependencies]
dev = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinxcontrib-apidoc"
]
ai = [
    "torch",
    "torchvision",
    "timm",
    "einops",
    "wandb",
    "scikit-learn"
]
allensdk = [
    "allensdk",
]
antspy = [
    'antspyx>=0.5.3',
]

all = [
    "liom_toolkit[ai]",
    "liom_toolkit[antspy]",
     "liom_toolkit[allensdk]",
]

[project.scripts]
liom-convert-hdf5-to-zarr = "liom_toolkit.scripts.liom_convert_hdf5_to_zarr:main"
liom-create-mask = "liom_toolkit.scripts.liom_create_mask:main"

[project.urls]
Homepage = "https://github.com/LIOMLab/liom-toolkit"
Documentation = "https://liom-toolkit.readthedocs.io/"
Repository = "https://github.com/LIOMLab/liom-toolkit"
