"""One-time fixture regeneration for the 100µm ITK-SNAP label regression test.

This script is NOT collected by pytest (no ``test_`` prefix, no pytest
functions). It is a gated one-time dev script that generates the committed
fixture (``labels.parquet`` + ``annotation_100um.npz`` + ``annotation_100.nrrd``
+ ``structure_tree.json``) used by
``tests/test_utils/test_allen_sdk.py::test_export_itksnap_labels_100um_matches_fixture``.

The 100µm atlas is used instead of the 25µm atlas because the 25µm annotation
volume (528x320x456 uint32, 308MB raw) made the regression test take ~7.4s,
dominated by the ``np.unique(return_inverse=True)`` remap over 77M voxels. The
100µm annotation (132x80x114, ~4.8MB) is ~64x smaller and the remap runs in
~0.04s, with no loss of regression coverage: the remap logic
(``_remap_to_id_type``) is resolution-independent, and the structure-tree
metadata (``labels.parquet``) is resolution-independent.

``labels.parquet`` and ``structure_tree.json`` are resolution-independent and
were originally generated by allensdk 2.16.2 (see the former 25µm fixture).
They are reused here unchanged — ``labels.parquet`` remains the byte-exact
allensdk oracle for the 8-column ITK-SNAP DataFrame. allensdk does not install
on Python 3.12+ (numpy 1.23.5 pin / ``numpy.distutils`` removed), so the
volume oracle (``annotation_100um.npz``) is a snapshot of the library's own
``export_itksnap_labels()`` output — a regression guard against unintended
changes to the remap logic, not an independent allensdk comparison. The
DataFrame check remains a true independent (allensdk) oracle.

Run manually:

    uv run python tests/test_utils/fixtures/allen_itksnap_100um/regenerate.py

This downloads the 100µm annotation NRRD via the library's own
``_download_nrrd`` (the Allen Institute CCFv3 endpoint), calls
``construct_reference_space(...).export_itksnap_labels()``, and saves the
resulting volume as the regression oracle. The structure-tree JSON and
labels.parquet are reused from the existing fixture (resolution-independent).
"""

from __future__ import annotations

import os
import shutil
import tempfile

import numpy as np
import pandas as pd

from liom_toolkit.utils.allen_sdk import (
    _ANNOTATION_URL,
    _download_nrrd,
    construct_reference_space,
)

FIXTURE_DIR = os.path.dirname(os.path.abspath(__file__))


def main() -> None:
    resolution = 100

    # The structure-tree JSON and labels.parquet are resolution-independent
    # and were originally generated by allensdk 2.16.2. They are committed to
    # the fixture dir and reused here unchanged — labels.parquet remains the
    # byte-exact allensdk oracle for the 8-column ITK-SNAP DataFrame.
    for name in ("structure_tree.json", "labels.parquet"):
        if not os.path.exists(os.path.join(FIXTURE_DIR, name)):
            raise FileNotFoundError(
                f"{name} not found in {FIXTURE_DIR}. This resolution-independent "
                "allensdk oracle must be present before regenerating the volume."
            )

    # Download the 100µm annotation NRRD via the library's own download path.
    nrrd_path = os.path.join(FIXTURE_DIR, f"annotation_{resolution}.nrrd")
    _download_nrrd(_ANNOTATION_URL.format(res=resolution), nrrd_path)

    # Build the reference space and export ITK-SNAP labels. Use a temp data_dir
    # so construct_reference_space finds the cached files under the names it
    # expects (allen_atlas_{res}.nrrd + structure_tree.json).
    with tempfile.TemporaryDirectory() as data_dir:
        shutil.copy(
            nrrd_path, os.path.join(data_dir, f"allen_atlas_{resolution}.nrrd")
        )
        shutil.copy(
            os.path.join(FIXTURE_DIR, "structure_tree.json"),
            os.path.join(data_dir, "structure_tree.json"),
        )
        rs = construct_reference_space(data_dir, resolution=resolution)
        vol, df = rs.export_itksnap_labels()

    # Sanity: the DataFrame must still match the allensdk oracle.
    expected_df = pd.read_parquet(os.path.join(FIXTURE_DIR, "labels.parquet"))
    pd.testing.assert_frame_equal(df, expected_df)

    # Save the volume oracle (compressed).
    np.savez_compressed(
        os.path.join(FIXTURE_DIR, f"annotation_{resolution}um.npz"), arr=vol
    )

    print(f"Fixture generated in {FIXTURE_DIR}:")
    print(f"  labels.parquet: {len(df)} rows, {df.shape[1]} columns (allensdk oracle)")
    print(
        f"  annotation_{resolution}um.npz: shape={vol.shape}, dtype={vol.dtype} "
        f"(library regression snapshot)"
    )
    print(f"  annotation_{resolution}.nrrd: cached for the regression test")
    print("  structure_tree.json: cached for the regression test")


if __name__ == "__main__":
    main()
